#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/types.h>
#include <regex.h>

// Feel free to change the data structures generated by AI.

#define MAX_SYSCALLS 1024
#define TOP_N 5

typedef struct {
    char name[64];
    double time;
} syscall_stat;

typedef struct {
    syscall_stat stats[MAX_SYSCALLS];
    int count;
    double total_time;
} syscall_stats;

int parse_strace_line(char *line, char *syscall_name, double *time) {
    char *parentesis_start = strchr(line, '(');
    if (!parentesis_start) {
        return -1;
    }
    size_t name_len = parentesis_start - line;
    strncpy(syscall_name, line, name_len);
    syscall_name[name_len] = '\0';

    regex_t regex;
    regmatch_t matches[2];
    regcomp(&regex, "<([0-9]+\\.[0-9]+)>", REG_EXTENDED);
    if (regexec(&regex, line, 2, matches, 0) == 0) {
        char time_str[32];
        size_t time_len = matches[1].rm_eo - matches[1].rm_so;
        strncpy(time_str, line + matches[1].rm_so, time_len);
        time_str[time_len] = '\0';
        *time = atof(time_str);
    } else {
        regfree(&regex);
        return -1;
    }
    regfree(&regex);
    return 0;
}

void add_syscall(syscall_stats *stats, const char *name, double time) {
    if (stats->count >= MAX_SYSCALLS) {
        return;
    }
    for (int i = 0; i < stats->count; i++) {
        if (strcmp(stats->stats[i].name, name) == 0) {
            stats->stats[i].time += time;
            stats->total_time += time;
            return;
        }
    }
    strncpy(stats->stats[stats->count].name, name, 64);
    stats->stats[stats->count].time = time;
    stats->total_time += time;
    stats->count++;
}

void print_top_syscalls(syscall_stats *stats, int n) {
    for (int i = 0; i < stats->count - 1; i++) {
        for (int j = 0; j < stats->count - i - 1; j++) {
            if (stats->stats[j].time < stats->stats[j + 1].time) {
                syscall_stat temp = stats->stats[j];
                stats->stats[j] = stats->stats[j + 1];
                stats->stats[j + 1] = temp;
            }
        }
    }

    for (int i = 0; i < n && i < stats->count; i++) {
        int ratio = (int)((stats->stats[i].time / stats->total_time) * 100);
        printf("%s (%d%%)\n", stats->stats[i].name, ratio);
    }

    char zeros[80] = {0};
    fwrite(zeros, 1, sizeof(zeros), stdout);
}

int main(int argc, char *argv[]) {
    int pipefd[2];

    if (pipe(pipefd) == -1) {
        perror("pipe");
        return 1;
    }

    pid_t pid = fork();
    if (pid == -1) {
        perror("fork");
        return 1;
    }

    if (pid == 0) {
        // Child process   
        // 1. close the read port
        close(pipefd[0]);
        // 2. redirect stderr to the write port
        dup2(pipefd[1], STDERR_FILENO);
        close(pipefd[1]);
        // 3. execute strace
        char *strace_argv[argc + 3]; // "strace", "-T", 原本的 argv[1..], NULL
        strace_argv[0] = "strace";
        strace_argv[1] = "-T";
        for (int i = 1; i < argc; i++) {
            strace_argv[i + 1] = argv[i];
        }
        strace_argv[argc + 1] = NULL;

        extern char **environ;
        execve("/usr/bin/strace", strace_argv, environ);
        perror("execve");
        exit(1);
    } else {
        // Parent process
        // 1. close the write port
        close(pipefd[1]);
        // 2. read from the read port
        FILE *fp = fdopen(pipefd[0], "r");
        char line[MAX_SYSCALLS];
        syscall_stats stats = {0};

        while (fgets(line, sizeof(line), fp)) {
            char syscall_name[64];
            double t;
            if (parse_strace_line(line, syscall_name, &t) == 0) {
                add_syscall(&stats, syscall_name, t);
            }
        }

        print_top_syscalls(&stats, TOP_N);

        fclose(fp);
    }
}
